@host = http://127.0.0.1:8000/collectors
@non_existing_collector = non_existing_collector
@valid_email = ab@gmail.com
@valid_email2 = abc@gmail.com
@valid_email3 = abcd@gmail.com
@wrong_email = wrong_email_format
@valid_username = TestCollector
@valid_username2 = Test Collector 2
@wrong_username = ab

### get all collectors
GET {{host}} HTTP/1.1

### ERROR: get non existing collector
GET {{host}}/{{non_existing_collector}} HTTP/1.1

### ERROR: create collector with incorrect email
POST {{host}} HTTP/1.1
Content-Type: application/json

{
  "username": "{{valid_username}}",
  "email": "{{wrong_email}}"
}

### ERROR: create collector with incorrect username
POST {{host}} HTTP/1.1
Content-Type: application/json

{
  "username": "{{wrong_username}}",
  "email": "{{valid_email}}"
}

### create collector
POST {{host}} HTTP/1.1
Content-Type: application/json

{
  "username": "{{valid_username}}",
  "email": "{{valid_email}}"
}

### get collector by username
GET {{host}}/{{valid_username}} HTTP/1.1

### ERROR: delete non existing collector
DELETE {{host}}/{{non_existing_collector}} HTTP/1.1

### create collector 2
POST {{host}} HTTP/1.1
Content-Type: application/json

{
  "username": "{{valid_username2}}",
  "email": "{{valid_email3}}"
}

### delete collector 2
DELETE {{host}}/{{valid_username2}} HTTP/1.1

### ERROR: update collector with incorrect email
PUT {{host}}/{{valid_username}} HTTP/1.1
Content-Type: application/json

{
  "email": "{{wrong_email}}"
}

### update collector email
PUT {{host}}/{{valid_username}} HTTP/1.1
Content-Type: application/json

{
  "email": "{{valid_email2}}"
}

### ERROR: update collector without email
PUT {{host}}/{{valid_username}} HTTP/1.1
Content-Type: application/json

{ }